AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'doc/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false
